---
title: "Data Import"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
library(haven)
```


##Load in the litters dataset 

```{r}
##reads in a dataset
litters_data = read_csv(file = "./data/FAS_litters.csv")
litters_data = janitor::clean_names(litters_data)
```

##Load in the pups dataset
```{r}
pups_data = read_csv(file = "./data/FAS_pups.csv")
pups_data = janitor::clean_names(pups_data)
```

##Parsing columns
```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv",
  col_types = cols(
    Group = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  ))
```

##Read in an excel file...
```{r}
mlb11_data = read_excel("./data/mlb11.xlsx", range = "A1:D7")
```

##Read in SAS...
```{r}
pulse_data = read_sas("./data/public_pulse_data.sas7bdat")
```