---
title: "Tidy Data"
author: "Martha Mulugeta"
date: "9/24/2019"
output: github_document
---
install.packages("tidyr")

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

##Wide to long
```{r}
pulse_data = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names() 
  
pulse_tidy_data = 
  pivot_longer(
    pulse_data, 
    bdi_score_bl:bdi_score_12m,
    names_to = "visit", 
    names_prefix = "bdi_score_",
    values_to = "bdi") %>% 

 select(id, visit, everything()) %>%
  mutate(
    visit = replace(visit, visit == "bl", "00m"),
    visit = factor(visit, levels = str_c(c("00", "01", "06", "12"), "m"))) %>%
  arrange(id, visit)

print(pulse_data, n = 12)
```

##Separate in litters 
```{r}
read_csv("./data/FAS_litters.csv") %>% 
  janitor::clean_names() %>%
  separate(col = group, into = c("dose", "day_of_tx"), 3)
```

##Pivot_wider, usually just for presentation purposes
```{r}
analysis_result = tibble(
  group = c("treatment", "treatment", "placebo", "placebo"),
  time = c("pre", "post", "pre", "post"),
  mean = c(4, 8, 3.5, 4)
)

##Variable names now time, cell values now means 
pivot_wider(
  analysis_result,
  names_from = time,
  values_from = mean
)
```

##Bind rows
```{r}
fellowship_data =
   readxl::read_excel("./data/LotR_Words.xlsx", range = "B3:D6") %>%
  mutate(movie = "fellowship_ring")

two_towers = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "F3:H6") %>%
  mutate(movie = "two_towers")

return_king = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "J3:L6") %>%
  mutate(movie = "return_king")

##Binding rows from one table to the next to the next
lotr_tidy = 
  bind_rows(fellowship_data, two_towers, return_king) %>%
  janitor::clean_names() %>%
  pivot_longer(
    female:male,
    names_to = "sex", 
    values_to = "words") %>%
  select(movie, everything()) 
```

```{r}
pup_data = 
  read_csv("./data/FAS_pups.csv", col_types = "ciiiii") %>%
  janitor::clean_names() %>%
  mutate(sex = recode(sex, `1` = "male", `2` = "female")) 

litter_data = 
  read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names() %>%
  select(-pups_survive) %>%
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group))
```

Try to join these datasets!! Start with pups data (complete) and tie in litters data. Wherever litter number is present in pups data and litter data
```{r}
fas_data = 
  left_join(pup_data, litter_data, by = "litter_number")
fas_data %>% view

full_join(pup_data, litter_data, by = "litter_number")
```



